- hosts: bahmni-emr-db
  sudo: yes
  roles:
    - { role: mysql }
  tags:
    - bahmni-emr-db

- hosts: bahmni-emr-db
  sudo: yes
  roles:
    - { role: mysql-users, db_user: "{{openmrs_db_username}}", db_password: "{{openmrs_db_password}}", database: openmrs, items: "{{groups['bahmni-emr']}}" }
    - { role: mysql-users, db_user: "{{openmrs_db_username}}", db_password: "{{openmrs_db_password}}", database: openmrs, items: "{{groups['bahmni-reports']}}", restrict_app_root: false }
  tags:
    - bahmni-emr-db

- hosts: mysql-backup-tool
  sudo: yes
  roles:
    - { role: mysql-backup-tool}
  tags:
    - mysql-backup-tool
